# 빌드 스테이지
FROM node:22-alpine AS builder

WORKDIR /app

# package.json 복사
COPY package*.json ./

# 캐시 정리 및 재설치
RUN npm cache clean --force
RUN npm install

# 포트 노출
EXPOSE 5173

# Vite 개발 서버 실행
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
